// This file is auto-generated by Supabase CLI
// Run: bun run db:generate to regenerate after schema changes

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          display_name: string
          avatar_url: string | null
          bio: string | null
          role: 'admin' | 'foodie' | 'public'
          is_verified: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          display_name: string
          avatar_url?: string | null
          bio?: string | null
          role?: 'admin' | 'foodie' | 'public'
          is_verified?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          display_name?: string
          avatar_url?: string | null
          bio?: string | null
          role?: 'admin' | 'foodie' | 'public'
          is_verified?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      restaurants: {
        Row: {
          id: string
          name: string
          slug: string
          description: string | null
          cuisine: string
          price_range: string
          address: string
          city: string
          state: string
          zip_code: string
          phone: string | null
          website: string | null
          latitude: number
          longitude: number
          image_url: string | null
          is_food_truck: boolean
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          description?: string | null
          cuisine: string
          price_range: string
          address: string
          city?: string
          state?: string
          zip_code: string
          phone?: string | null
          website?: string | null
          latitude: number
          longitude: number
          image_url?: string | null
          is_food_truck?: boolean
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          description?: string | null
          cuisine?: string
          price_range?: string
          address?: string
          city?: string
          state?: string
          zip_code?: string
          phone?: string | null
          website?: string | null
          latitude?: number
          longitude?: number
          image_url?: string | null
          is_food_truck?: boolean
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      reviews: {
        Row: {
          id: string
          restaurant_id: string
          reviewer_id: string
          rating: number
          content: string | null
          photos: string[] | null
          menu_items: string[] | null
          is_foodie_review: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          restaurant_id: string
          reviewer_id: string
          rating: number
          content?: string | null
          photos?: string[] | null
          menu_items?: string[] | null
          is_foodie_review?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          restaurant_id?: string
          reviewer_id?: string
          rating?: number
          content?: string | null
          photos?: string[] | null
          menu_items?: string[] | null
          is_foodie_review?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      menu_items: {
        Row: {
          id: string
          restaurant_id: string
          name: string
          description: string | null
          price: number | null
          image_url: string | null
          created_at: string
        }
        Insert: {
          id?: string
          restaurant_id: string
          name: string
          description?: string | null
          price?: number | null
          image_url?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          restaurant_id?: string
          name?: string
          description?: string | null
          price?: number | null
          image_url?: string | null
          created_at?: string
        }
      }
      menu_recommendations: {
        Row: {
          id: string
          menu_item_id: string
          reviewer_id: string
          review_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          menu_item_id: string
          reviewer_id: string
          review_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          menu_item_id?: string
          reviewer_id?: string
          review_id?: string | null
          created_at?: string
        }
      }
      foodie_applications: {
        Row: {
          id: string
          user_id: string
          status: 'pending' | 'approved' | 'rejected'
          application_text: string
          reviewed_by: string | null
          reviewed_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          status?: 'pending' | 'approved' | 'rejected'
          application_text: string
          reviewed_by?: string | null
          reviewed_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          status?: 'pending' | 'approved' | 'rejected'
          application_text?: string
          reviewed_by?: string | null
          reviewed_at?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      restaurant_ratings: {
        Row: {
          restaurant_id: string
          foodie_rating: number | null
          public_rating: number | null
          overall_rating: number | null
          foodie_review_count: number
          public_review_count: number
          total_review_count: number
        }
      }
      menu_item_recommendations_count: {
        Row: {
          menu_item_id: string
          restaurant_id: string
          name: string
          recommendation_count: number
        }
      }
    }
    Functions: {
      is_admin: {
        Args: Record<string, never>
        Returns: boolean
      }
      is_foodie: {
        Args: Record<string, never>
        Returns: boolean
      }
    }
    Enums: {
      user_role: 'admin' | 'foodie' | 'public'
      application_status: 'pending' | 'approved' | 'rejected'
    }
  }
}
