/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as FoodiesRouteImport } from './routes/foodies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RestaurantsIdRouteImport } from './routes/restaurants.$id'
import { Route as FoodiesIdRouteImport } from './routes/foodies.$id'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminRestaurantsRouteImport } from './routes/admin/restaurants'
import { Route as AdminRestaurantsNewRouteImport } from './routes/admin/restaurants.new'
import { Route as AdminRestaurantsIdRouteImport } from './routes/admin/restaurants.$id'

const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodiesRoute = FoodiesRouteImport.update({
  id: '/foodies',
  path: '/foodies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIdRoute = RestaurantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RestaurantsRoute,
} as any)
const FoodiesIdRoute = FoodiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FoodiesRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRestaurantsRoute = AdminRestaurantsRouteImport.update({
  id: '/admin/restaurants',
  path: '/admin/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRestaurantsNewRoute = AdminRestaurantsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRestaurantsRoute,
} as any)
const AdminRestaurantsIdRoute = AdminRestaurantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminRestaurantsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/foodies': typeof FoodiesRouteWithChildren
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/admin/restaurants': typeof AdminRestaurantsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/foodies/$id': typeof FoodiesIdRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/restaurants/$id': typeof AdminRestaurantsIdRoute
  '/admin/restaurants/new': typeof AdminRestaurantsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/foodies': typeof FoodiesRouteWithChildren
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/admin/restaurants': typeof AdminRestaurantsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/foodies/$id': typeof FoodiesIdRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/restaurants/$id': typeof AdminRestaurantsIdRoute
  '/admin/restaurants/new': typeof AdminRestaurantsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/foodies': typeof FoodiesRouteWithChildren
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/admin/restaurants': typeof AdminRestaurantsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/foodies/$id': typeof FoodiesIdRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/restaurants/$id': typeof AdminRestaurantsIdRoute
  '/admin/restaurants/new': typeof AdminRestaurantsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/foodies'
    | '/restaurants'
    | '/admin/restaurants'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/foodies/$id'
    | '/restaurants/$id'
    | '/admin'
    | '/admin/restaurants/$id'
    | '/admin/restaurants/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/foodies'
    | '/restaurants'
    | '/admin/restaurants'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/foodies/$id'
    | '/restaurants/$id'
    | '/admin'
    | '/admin/restaurants/$id'
    | '/admin/restaurants/new'
  id:
    | '__root__'
    | '/'
    | '/foodies'
    | '/restaurants'
    | '/admin/restaurants'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/foodies/$id'
    | '/restaurants/$id'
    | '/admin/'
    | '/admin/restaurants/$id'
    | '/admin/restaurants/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FoodiesRoute: typeof FoodiesRouteWithChildren
  RestaurantsRoute: typeof RestaurantsRouteWithChildren
  AdminRestaurantsRoute: typeof AdminRestaurantsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foodies': {
      id: '/foodies'
      path: '/foodies'
      fullPath: '/foodies'
      preLoaderRoute: typeof FoodiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$id': {
      id: '/restaurants/$id'
      path: '/$id'
      fullPath: '/restaurants/$id'
      preLoaderRoute: typeof RestaurantsIdRouteImport
      parentRoute: typeof RestaurantsRoute
    }
    '/foodies/$id': {
      id: '/foodies/$id'
      path: '/$id'
      fullPath: '/foodies/$id'
      preLoaderRoute: typeof FoodiesIdRouteImport
      parentRoute: typeof FoodiesRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/restaurants': {
      id: '/admin/restaurants'
      path: '/admin/restaurants'
      fullPath: '/admin/restaurants'
      preLoaderRoute: typeof AdminRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/restaurants/new': {
      id: '/admin/restaurants/new'
      path: '/new'
      fullPath: '/admin/restaurants/new'
      preLoaderRoute: typeof AdminRestaurantsNewRouteImport
      parentRoute: typeof AdminRestaurantsRoute
    }
    '/admin/restaurants/$id': {
      id: '/admin/restaurants/$id'
      path: '/$id'
      fullPath: '/admin/restaurants/$id'
      preLoaderRoute: typeof AdminRestaurantsIdRouteImport
      parentRoute: typeof AdminRestaurantsRoute
    }
  }
}

interface FoodiesRouteChildren {
  FoodiesIdRoute: typeof FoodiesIdRoute
}

const FoodiesRouteChildren: FoodiesRouteChildren = {
  FoodiesIdRoute: FoodiesIdRoute,
}

const FoodiesRouteWithChildren =
  FoodiesRoute._addFileChildren(FoodiesRouteChildren)

interface RestaurantsRouteChildren {
  RestaurantsIdRoute: typeof RestaurantsIdRoute
}

const RestaurantsRouteChildren: RestaurantsRouteChildren = {
  RestaurantsIdRoute: RestaurantsIdRoute,
}

const RestaurantsRouteWithChildren = RestaurantsRoute._addFileChildren(
  RestaurantsRouteChildren,
)

interface AdminRestaurantsRouteChildren {
  AdminRestaurantsIdRoute: typeof AdminRestaurantsIdRoute
  AdminRestaurantsNewRoute: typeof AdminRestaurantsNewRoute
}

const AdminRestaurantsRouteChildren: AdminRestaurantsRouteChildren = {
  AdminRestaurantsIdRoute: AdminRestaurantsIdRoute,
  AdminRestaurantsNewRoute: AdminRestaurantsNewRoute,
}

const AdminRestaurantsRouteWithChildren =
  AdminRestaurantsRoute._addFileChildren(AdminRestaurantsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FoodiesRoute: FoodiesRouteWithChildren,
  RestaurantsRoute: RestaurantsRouteWithChildren,
  AdminRestaurantsRoute: AdminRestaurantsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
